POST http://localhost:3333/events
Content-Type: application/json

{
    "title": "Novo evento2",
    "details": null,
    "maximumAttendees": 1
}

###

POST http://localhost:3333/events/8aa8932b-f4f3-411b-8be5-941ac1f59bd2/attendees
Content-Type:  application/json

{
    "name": "André Caracioly",
    "email": "andre2@email.com"
}

###

GET http://localhost:3333/events/8aa8932b-f4f3-411b-8be5-941ac1f59bd2

###

GET http://localhost:3333/attendees/8/badge